### ISSUE TITLE
Missing openssl.cnf configuration

### ISSUE THREAD

**Issue by afogg01** [WorkloadAutomation/ibm-workload-automation-chart#1]
Under the section 'Securing communication', the second command to create the CA references an openssl config file that is not described elsewhere in the documentation or provided in the repository files, thus causing the command to fail:

```.\openssl.exe req -x509 -new -nodes -key ca.key -subj "/CN=WA_ROOT_CA" -days 3650 -out ca.crt -config .\openssl.cnf```

```
Can't open .openssl.cfg for reading, No such file or directory
140502523168064:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('.openssl.cfg','r')
140502523168064:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
```

**Comment by psini** [comment]
Changed the readme to not use  -config .\openssl.cnf
