### ISSUE TITLE
Version in annotation out of sequence?

### ISSUE THREAD

**Issue by afogg01** [WorkloadAutomation/ibm-workload-automation-chart#38]
https://github.com/WorkloadAutomation/ibm-workload-automation-chart/blob/876c523eed2fbbe3b91e1da8d484a3e272e7c842/helm_charts/ibm-workload-automation-prod/charts/wa-console-prod/templates/statefulSet.yaml#L39

Should this annotation be set to 10.2? I don't see it set in the charts for server or agent, so unsure if there's any functional issue with this annotation being set.

**Comment by psini** [comment]
Thats not a big issue is only to track the produce version

Il Gio 14 Nov 2024, 14:16 Andy Fogg ***@***.***> ha scritto:
